var h = require('fs').readFileSync('index.html', 'utf8');
console.log('rotation:', h.indexOf('getRotation') > -1);
console.log('canvas 500x200:', h.indexOf('width="500"') > -1);
console.log('sigTextInput:', h.indexOf('sigTextInput') > -1);
console.log('fillText:', h.indexOf('fillText(text') > -1);
console.log('autoFitText:', h.indexOf('function autoFitText') > -1);
console.log('autoFit resize:', h.indexOf('autoFitText(box') > -1);
console.log('btn Guardar:', h.indexOf('Guardar</button>') > -1);
console.log('fontSize 72:', h.indexOf('fontSize: 72') > -1);
console.log('no textFontSize label:', h.indexOf('id="textFontSize"') === -1);
